import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalProvider } from "@/context/store";
import 'primeflex/primeflex.css';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LB-LAPTOPS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </GlobalProvider>
  );
}
